workflows:
  build-app:
    name: ProposalFast Build
    environment:
      node: 18
    triggering:
      events:
        - push
      branch:
        include:
          - main
    scripts:
      - name: Install
        script: npm install --legacy-peer-deps
      - name: Build Android
        script: npm run build:android
      - name: Build iOS
        script: npm run build:ios
