workflows:
  react-native:
    name: React Native Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 18
      xcode: latest
    triggering:
      events:
        - push
      branch:
        pattern: 'main'
    scripts:
      - name: Install
        script: npm install
      - name: Build
        script: npm run build
